experiment_name: "test1"
environment:
  class_path: atcenv.src.environment_objects.environment.DefaultEnvironment
  init_args:
    render_frequency: 1
model:
  class_path: atcenv.src.models.model.Random
  init_args:
    action_dim: 2
scenario:
  num_episodes: 1000
  num_flights: 20
  airspace_area: 10000000000
  traffic_density: 0
  test_scenario_dir: "hello"
  num_test_episodes: 0
  test_frequency: 0
  random_seed: 1
airspace:
  class_path: atcenv.src.environment_objects.airspace.EnrouteAirspace
aircraft:
  min_speed: 200
  max_speed: 250
  min_distance: 10000
observation:
  class_path: atcenv.src.observation.observation.BasicRel
  init_args:
    observation_size: 18
    num_ac_state: 3
    normalize_data: False
    create_normalization_data: False
    normalization_data_file: "basic_rel_normalization.p"
    normalization_samples: 500000
reward:
  class_path: atcenv.src.reward.reward.DefaultReward
logger:
  class_path: atcenv.src.logger.logger.BasicLogger
  init_args:
    log_frequency: 1
    verbose: True
